Gerende.create(name: 'ルスツリゾート', prefecture_id: '1')
Gerende.create(name: '富良野スキー場', prefecture_id: '1')
Gerende.create(name: '星野リゾート　トマム　スキー場', prefecture_id: '1')
Gerende.create(name: '函館七飯スノーパーク', prefecture_id: '1')
Gerende.create(name: 'ニセコマウンテンリゾート　グラン・ヒラフ', prefecture_id: '1')
Gerende.create(name: 'ニセコHANZONOリゾート', prefecture_id: '1')
Gerende.create(name: 'サッポロテイネ', prefecture_id: '1')
Gerende.create(name: 'KIRORO SNOW WORLD', prefecture_id: '1')
Gerende.create(name: '札幌町民スキー場　びゅー', prefecture_id: '1')
Gerende.create(name: '中頓別寿スキー場', prefecture_id: '1')
Gerende.create(name: '札幌藻岩山スキー場', prefecture_id: '1')
Gerende.create(name: 'サンタプレゼントパーク　マロースゲレンデ', prefecture_id: '1')
Gerende.create(name: 'ニセコモイワスキーリゾート', prefecture_id: '1')
Gerende.create(name: '三笠桂沢国設スキー場', prefecture_id: '1')
Gerende.create(name: 'ニセコアンヌプリ国際スキー場', prefecture_id: '1')
Gerende.create(name: 'サホロリゾートスキー場', prefecture_id: '1')
Gerende.create(name: 'カムイスキーリンクス', prefecture_id: '1')
Gerende.create(name: '北見市留辺蘂町　八方大スキー場', prefecture_id: '1')
Gerende.create(name: '和寒町東山スキー場', prefecture_id: '1')
Gerende.create(name: '大雪山　黒岳スキー場', prefecture_id: '1')
Gerende.create(name: 'セコビレッジスキーリゾート', prefecture_id: '1')
Gerende.create(name: 'マウントレースイスキーリゾート', prefecture_id: '1')
Gerende.create(name: 'キャンモアスキービレッジ', prefecture_id: '1')
Gerende.create(name: 'さっぽろばんけいスキー場', prefecture_id: '1')
Gerende.create(name: 'ぴっぷスキー場', prefecture_id: '1')
Gerende.create(name: '国設芦別スキー場', prefecture_id: '1')
Gerende.create(name: '置戸町南ヶ丘スキー場', prefecture_id: '1')
Gerende.create(name: '小樽天狗山スキー場', prefecture_id: '1')
Gerende.create(name: 'ウィンザースノービレッジ', prefecture_id: '1')
Gerende.create(name: '中山峠スキー場', prefecture_id: '1')
Gerende.create(name: 'SNOW CRUISE ONZE', prefecture_id: '1')
Gerende.create(name: 'ダイナスティスキーリゾート', prefecture_id: '1')
Gerende.create(name: '朝里川温泉スキー場', prefecture_id: '1')
Gerende.create(name: '今金町ピリカスキー場', prefecture_id: '1')
Gerende.create(name: '札幌国際スキー場', prefecture_id: '1')
Gerende.create(name: '名寄ピヤシリスキー場', prefecture_id: '1')
Gerende.create(name: '豊富温泉スキー場', prefecture_id: '1')
Gerende.create(name: '士別市　日向スキー場', prefecture_id: '1')
Gerende.create(name: '士別市あさひスキー場', prefecture_id: '1')
Gerende.create(name: '沼田町営高穂スキー場', prefecture_id: '1')
Gerende.create(name: '暑寒別岳スキー場', prefecture_id: '1')
Gerende.create(name: '中富良野北星スキー場', prefecture_id: '1')
Gerende.create(name: '幌延町東ヶ丘スキー場', prefecture_id: '1')
Gerende.create(name: '上川町営中山スキー場', prefecture_id: '1')
Gerende.create(name: '稚内市こまどりスキー場', prefecture_id: '1')
Gerende.create(name: '枝幸町三笠山スキー場', prefecture_id: '1')
Gerende.create(name: 'とうま山スキー場', prefecture_id: '1')
Gerende.create(name: '安平山スキー場', prefecture_id: '1')
Gerende.create(name: '忠類白銀台スキー場', prefecture_id: '1')
Gerende.create(name: '明野ヶ丘スキー場', prefecture_id: '1')
Gerende.create(name: '佐呂間町営スキー場', prefecture_id: '1')
Gerende.create(name: '北見若松市民スキー場', prefecture_id: '1')
Gerende.create(name: '標津町営金山スキー場', prefecture_id: '1')
Gerende.create(name: 'メムロスキー場', prefecture_id: '1')
Gerende.create(name: '紋別市営大山スキー場', prefecture_id: '1')
Gerende.create(name: '清里町営緑スキー場', prefecture_id: '1')
Gerende.create(name: 'IWANAI RESORT', prefecture_id: '1')
Gerende.create(name: 'Fu’s snow area', prefecture_id: '1')
Gerende.create(name: 'ほろたちスキー場', prefecture_id: '1')
Gerende.create(name: '美唄国設スキー場', prefecture_id: '1')
Gerende.create(name: '岩見沢萩の山市民スキー場', prefecture_id: '1')
Gerende.create(name: '長沼スキー場', prefecture_id: '1')
Gerende.create(name: '日高国際スキー場', prefecture_id: '1')
Gerende.create(name: '仁木町民スキー場', prefecture_id: '1')
Gerende.create(name: 'オロフレスキー場', prefecture_id: '1')
Gerende.create(name: '倶知安町旭ヶ丘スキー場', prefecture_id: '1')
Gerende.create(name: 'そっち岳スキー場', prefecture_id: '1')
Gerende.create(name: 'ニヤマ高原スキー場', prefecture_id: '1')
Gerende.create(name: '石狩平原スキー場', prefecture_id: '1')
Gerende.create(name: 'カルルス温泉サンライバスキー場', prefecture_id: '1')
Gerende.create(name: '国設南ふらのスキー場', prefecture_id: '1')
Gerende.create(name: '国設阿寒湖畔スキー場「ウタラ」', prefecture_id: '1')
Gerende.create(name: 'ぬかびら源泉郷スキー場', prefecture_id: '1')
Gerende.create(name: '音威富士スキー場', prefecture_id: '1')
Gerende.create(name: 'グリーンピア大沼スキー場', prefecture_id: '1')
Gerende.create(name: '湧別町　五鹿山スキー場', prefecture_id: '1')
Gerende.create(name: '滝野スノーワールド', prefecture_id: '1')
Gerende.create(name: 'かもい岳スキー場', prefecture_id: '1')
Gerende.create(name: '阿寒ロイヤルバレイスキー場', prefecture_id: '1')
Gerende.create(name: '網走レークビュースキー場', prefecture_id: '1')
Gerende.create(name: '伊ノ沢市民スキー場', prefecture_id: '1')
Gerende.create(name: 'んがるロックバレースキー場', prefecture_id: '1')
Gerende.create(name: '部町営スキー場', prefecture_id: '1')
Gerende.create(name: '小平町望洋台スキー場', prefecture_id: '1')
Gerende.create(name: '富良野町日の出スキー場', prefecture_id: '1')
Gerende.create(name: '斜里町ウナベツスキー場', prefecture_id: '1')
Gerende.create(name: '知内町営スキー場', prefecture_id: '1')
Gerende.create(name: '新得山スキー場', prefecture_id: '1')
Gerende.create(name: '滝上町桜ヶ丘スキー場', prefecture_id: '1')
Gerende.create(name: 'チセヌプリスキー場', prefecture_id: '1')
Gerende.create(name: '天塩町町民スキー場', prefecture_id: '1')
Gerende.create(name: '美深スキー場', prefecture_id: '1')
Gerende.create(name: '美幌町リリー山スキー場', prefecture_id: '1')
Gerende.create(name: '北海法グリーンランドホワイトパーク', prefecture_id: '1')
Gerende.create(name: '室蘭市高原だんパラスキー場 ', prefecture_id: '1')
Gerende.create(name: '青森スプリング・スキーリゾート', prefecture_id: '2')
Gerende.create(name: '創遊村229スキーランド', prefecture_id: '2')
Gerende.create(name: 'まかど温泉スキー場', prefecture_id: '2')
Gerende.create(name: '大鰐温泉スキー場', prefecture_id: '2')
Gerende.create(name: '八甲田スキー場', prefecture_id: '2')
Gerende.create(name: 'むつ市釜臥山スキー場', prefecture_id: '2')
Gerende.create(name: '十和田湖温泉スキー場', prefecture_id: '2')
Gerende.create(name: 'そうまロマントピアスキー場', prefecture_id: '2')
Gerende.create(name: '岩木山百沢スキー場', prefecture_id: '2')
Gerende.create(name: '七戸町営スキー場', prefecture_id: '2')
Gerende.create(name: 'モヤヒルズ', prefecture_id: '2')
Gerende.create(name: '夜越山スキー場', prefecture_id: '2')
Gerende.create(name: '安比高原スキー場', prefecture_id: '3')
Gerende.create(name: '夏油高原スキー場', prefecture_id: '3')
Gerende.create(name: '岩手高原スノーパーク', prefecture_id: '3')
Gerende.create(name: '雫石スキー場', prefecture_id: '3')
Gerende.create(name: '八幡平リゾート　パノラマスキー場＆下倉スキー場', prefecture_id: '3')
Gerende.create(name: '奥中山高原スキー場', prefecture_id: '3')
Gerende.create(name: 'ひめゆかスキー場', prefecture_id: '3')
Gerende.create(name: '網張温泉スキー場', prefecture_id: '3')
Gerende.create(name: '八幡平市　田山スキー場', prefecture_id: '3')
Gerende.create(name: '町営湯田スキー場', prefecture_id: '3')
Gerende.create(name: '平庭高原スキー場', prefecture_id: '3')
Gerende.create(name: '国見平スキー場', prefecture_id: '3')
Gerende.create(name: '奥州市越路スキー場', prefecture_id: '3')
Gerende.create(name: '赤羽根スキー場', prefecture_id: '3')
Gerende.create(name: 'くのへスキー場', prefecture_id: '3')
Gerende.create(name: '花巻市鉛温泉スキー場', prefecture_id: '3')
Gerende.create(name: 'スプリングバレー仙台泉スキー場', prefecture_id: '4')
Gerende.create(name: 'オニコウベスキー場', prefecture_id: '4')
Gerende.create(name: 'みやぎ蔵王えぼしリゾート', prefecture_id: '4')
Gerende.create(name: 'みやぎ蔵王白石スキー場', prefecture_id: '4')
Gerende.create(name: 'みやぎ蔵王七ヶ宿スキー場', prefecture_id: '4')
Gerende.create(name: '泉ヶ岳スキー場', prefecture_id: '4')
Gerende.create(name: 'やくらいファミリースキー場', prefecture_id: '4')
Gerende.create(name: 'みやぎ蔵王スキー場　すみかわスノーパーク', prefecture_id: '4')
Gerende.create(name: 'みやぎ蔵王セントメリースキー場', prefecture_id: '4')
Gerende.create(name: '上野々スキー場', prefecture_id: '4')
Gerende.create(name: '鳥海高原矢島スキー場', prefecture_id: '5')
Gerende.create(name: '水晶山スキー場', prefecture_id: '5')
Gerende.create(name: '秋田八幡平スキー場', prefecture_id: '5')
Gerende.create(name: '太平山スキー場　オーパス', prefecture_id: '5')
Gerende.create(name: 'たざわ湖スキー場', prefecture_id: '5')
Gerende.create(name: '大仙市営協和スキー場', prefecture_id: '5')
Gerende.create(name: '藤里町営スキー場', prefecture_id: '5')
Gerende.create(name: '稲川スキー場', prefecture_id: '5')
Gerende.create(name: '花輪スキー場', prefecture_id: '5')
Gerende.create(name: '大仙市営大曲ファミリースキー場', prefecture_id: '5')
Gerende.create(name: '大仙市営大台スキー場', prefecture_id: '5')
Gerende.create(name: 'ジュネス栗駒スキー場', prefecture_id: '5')
Gerende.create(name: '阿仁スキー場', prefecture_id: '5')
Gerende.create(name: '横手市天下森スキー場', prefecture_id: '5')
Gerende.create(name: '黒伏高原スノーパーク　ジャングル・ジャングル', prefecture_id: '6')
Gerende.create(name: '天元台高原', prefecture_id: '6')
Gerende.create(name: '蔵王温泉スキー場', prefecture_id: '6')
Gerende.create(name: 'グリーンバレー神室スキー場', prefecture_id: '6')
Gerende.create(name: '天童高原スキー場', prefecture_id: '6')
Gerende.create(name: 'Asahi自然観　SNOW PARK', prefecture_id: '6')
Gerende.create(name: '湯殿山スキー場', prefecture_id: '6')
Gerende.create(name: '蔵王ライザワールド', prefecture_id: '6')
Gerende.create(name: '羽黒山スキー場', prefecture_id: '6')
Gerende.create(name: '白鷹町営スキー場', prefecture_id: '6')
Gerende.create(name: '蔵王猿倉スキー場', prefecture_id: '6')
Gerende.create(name: '月山スキー場', prefecture_id: '6')
Gerende.create(name: '米沢スキー場', prefecture_id: '6')
Gerende.create(name: 'やまがた　赤倉温泉スキー場', prefecture_id: '6')
Gerende.create(name: '新庄市民スキー場', prefecture_id: '6')
Gerende.create(name: '櫛引たらのきだいスキー場', prefecture_id: '6')
Gerende.create(name: '松山スキー場', prefecture_id: '6')
Gerende.create(name: '西川町民スキー場', prefecture_id: '6')
Gerende.create(name: '小国町横根スキー場', prefecture_id: '6')
Gerende.create(name: '小野川温泉スキー場', prefecture_id: '6')
Gerende.create(name: '手ノ子スキー場', prefecture_id: '6')
Gerende.create(name: '花笠高原スキー場', prefecture_id: '6')
Gerende.create(name: 'グランデコスノーリゾート', prefecture_id: '7')
Gerende.create(name: '猪苗代スキー場', prefecture_id: '7')
Gerende.create(name: '箕輪スキー場', prefecture_id: '7')
Gerende.create(name: '会津高原たかつえスキー場', prefecture_id: '7')
Gerende.create(name: '会津高原高畑スキー場', prefecture_id: '7')
Gerende.create(name: 'グランディ羽鳥湖スキーリゾート', prefecture_id: '7')
Gerende.create(name: '会津高原だいくらスキー場', prefecture_id: '7')
Gerende.create(name: '星野リゾート　猫魔スキー場', prefecture_id: '7')
Gerende.create(name: '星野リゾート　アルツ磐梯', prefecture_id: '7')
Gerende.create(name: '会津高原南郷スキー場', prefecture_id: '7')
Gerende.create(name: '尾瀬檜枝岐温泉スキー場', prefecture_id: '7')
Gerende.create(name: '沼尻スキー場', prefecture_id: '7')
Gerende.create(name: 'あただら高原スキー場', prefecture_id: '7')
Gerende.create(name: 'リステルスキーファンタジア', prefecture_id: '7')
Gerende.create(name: 'ファミリースノーパーク　ばんだい×２', prefecture_id: '7')
Gerende.create(name: '猪苗代リゾートスキー', prefecture_id: '7')
Gerende.create(name: '裏磐梯スキー場', prefecture_id: '7')
Gerende.create(name: '二本松塩沢スキー場', prefecture_id: '7')
Gerende.create(name: '喜多方市三ノ倉スキー場', prefecture_id: '7')
Gerende.create(name: 'スキーリゾート天栄', prefecture_id: '7')
Gerende.create(name: '只見スキー場', prefecture_id: '7')
Gerende.create(name: 'フェアリーランドかねやまスキー場', prefecture_id: '7')
Gerende.create(name: '横向温泉スキー場', prefecture_id: '7')
Gerende.create(name: 'ハンターマウンテン塩原', prefecture_id: '9')
Gerende.create(name: 'マウントジーンズ那須', prefecture_id: '9')
Gerende.create(name: '日光湯元温泉スキー場', prefecture_id: '9')
Gerende.create(name: 'エーデルワイススキー場', prefecture_id: '9')
Gerende.create(name: '那須温泉ファミリースキー場', prefecture_id: '9')
Gerende.create(name: '奥利根スノーパーク', prefecture_id: '10')
Gerende.create(name: 'たんばらスキーパーク', prefecture_id: '10')
Gerende.create(name: 'ノルン水上スキー場', prefecture_id: '10')
Gerende.create(name: 'ホワイトワールド尾瀬岩鞍', prefecture_id: '10')
Gerende.create(name: '川場スキー場', prefecture_id: '10')
Gerende.create(name: '水上高原スキーリゾート', prefecture_id: '10')
Gerende.create(name: '軽井沢スノーパーク', prefecture_id: '10')
Gerende.create(name: '水上宝台樹スキー場', prefecture_id: '10')
Gerende.create(name: 'パルコールつま恋スキーリゾート', prefecture_id: '10')
Gerende.create(name: '丸沼高原スキー場', prefecture_id: '10')
Gerende.create(name: '水上高原・奥利根温泉　藤原スキー場', prefecture_id: '10')
Gerende.create(name: '万座温泉スキー場', prefecture_id: '10')
Gerende.create(name: 'かたしな高原スキー場', prefecture_id: '10')
Gerende.create(name: '草津温泉スキー場', prefecture_id: '10')
Gerende.create(name: 'ホワイトバレースキー場', prefecture_id: '10')
Gerende.create(name: 'オグナほたかスキー場スノーパーク尾瀬戸倉', prefecture_id: '10')
Gerende.create(name: '鹿沢スノーエリア', prefecture_id: '10')
Gerende.create(name: 'みなかみ町営赤沢スキー場', prefecture_id: '10')
Gerende.create(name: 'ホテルヴィレッジ森のスキー場', prefecture_id: '10')
Gerende.create(name: '赤城山　第一スキー場', prefecture_id: '10')
Gerende.create(name: '谷川岳天神平スキー場', prefecture_id: '10')
Gerende.create(name: '狭山スキー場', prefecture_id: '11')
Gerende.create(name: 'スノーヴァ新横浜', prefecture_id: '14')
Gerende.create(name: '赤倉温泉スキー場', prefecture_id: '15')
Gerende.create(name: '舞子スノーリゾート', prefecture_id: '15')
Gerende.create(name: 'キューピットバレイ', prefecture_id: '15')
Gerende.create(name: 'ムイカスノーリゾート', prefecture_id: '15')
Gerende.create(name: 'ロッテアライリゾート', prefecture_id: '15')
Gerende.create(name: '湯沢中里スノーリゾート', prefecture_id: '15')
Gerende.create(name: '苗場スキー上', prefecture_id: '15')
Gerende.create(name: '神立スノーリゾート', prefecture_id: '15')
Gerende.create(name: '上越国際スキー場', prefecture_id: '15')
Gerende.create(name: '妙高杉ノ原スキー場', prefecture_id: '15')
Gerende.create(name: 'NASPAスキーガーデン', prefecture_id: '15')
Gerende.create(name: '湯沢パークスキー場', prefecture_id: '15')
Gerende.create(name: 'かぐらスキー場', prefecture_id: '15')
Gerende.create(name: '湯沢高原スキー場', prefecture_id: '15')
Gerende.create(name: 'GALA湯沢スキー場', prefecture_id: '15')
Gerende.create(name: '石打丸山スキー場', prefecture_id: '15')
Gerende.create(name: 'シャルマン火打スキー場', prefecture_id: '15')
Gerende.create(name: '六日町八海山スキー場', prefecture_id: '15')
Gerende.create(name: '奥只見丸山スキー場', prefecture_id: '15')
Gerende.create(name: 'ニュー・グリーンピア津南スキー場', prefecture_id: '15')
Gerende.create(name: '岩原スキー場', prefecture_id: '15')
Gerende.create(name: '須原スキー場', prefecture_id: '15')
Gerende.create(name: '池の平温泉スキー場', prefecture_id: '15')
Gerende.create(name: 'ニノックススノーパーク', prefecture_id: '15')
Gerende.create(name: '赤倉観光リゾートスキー場', prefecture_id: '15')
Gerende.create(name: '小出スキー場', prefecture_id: '15')
Gerende.create(name: '三川・温泉スキー場', prefecture_id: '15')
Gerende.create(name: '松之山温泉スキー場', prefecture_id: '15')
Gerende.create(name: 'とちおファミリースキー場', prefecture_id: '15')
Gerende.create(name: '松代ファミリースキー場', prefecture_id: '15')
Gerende.create(name: '湯沢一本杉スキー場', prefecture_id: '15')
Gerende.create(name: '糸魚川シーサイドバレースキー場', prefecture_id: '15')
Gerende.create(name: '休暇村妙高　ルンルンスキー場', prefecture_id: '15')
Gerende.create(name: '高柳ガルルのスキー場', prefecture_id: '15')
Gerende.create(name: '八海山麓スキー場', prefecture_id: '15')
Gerende.create(name: 'シャトー塩沢', prefecture_id: '15')
Gerende.create(name: 'なかさと清津スキー場', prefecture_id: '15')
Gerende.create(name: '魚沼大原スキー場', prefecture_id: '15')
Gerende.create(name: '石打花岡スキー場', prefecture_id: '15')
Gerende.create(name: '金谷山スキー場', prefecture_id: '15')
Gerende.create(name: '関温泉スキー場', prefecture_id: '15')
Gerende.create(name: '胎内スキー場', prefecture_id: '15')
Gerende.create(name: '薬師スキー場', prefecture_id: '15')
Gerende.create(name: '長岡市営スキー場', prefecture_id: '15')
Gerende.create(name: 'わぶかな高原スキー場', prefecture_id: '15')
Gerende.create(name: '大湯温泉スキー場', prefecture_id: '15')
Gerende.create(name: '村上市　ぶどうスキー場', prefecture_id: '15')
Gerende.create(name: '妙高スキーパーク', prefecture_id: '15')
Gerende.create(name: '五日町スキー場', prefecture_id: '15')
Gerende.create(name: '古志高原スキー場', prefecture_id: '15')
Gerende.create(name: '中里スノーウッドスキー場', prefecture_id: '15')
Gerende.create(name: 'Mt.グランビュー', prefecture_id: '15')
Gerende.create(name: '牛岳温泉スキー場', prefecture_id: '16')
Gerende.create(name: 'たいらスキー場', prefecture_id: '16')
Gerende.create(name: 'となみ夢の平スキー場', prefecture_id: '16')
Gerende.create(name: 'IOXーAROSA', prefecture_id: '16')
Gerende.create(name: '立山山麓スキー場', prefecture_id: '16')
Gerende.create(name: 'タカンボースキー場', prefecture_id: '16')
Gerende.create(name: '宇奈月温泉スキー場', prefecture_id: '16')
Gerende.create(name: '白山一里野温泉スキー場', prefecture_id: '17')
Gerende.create(name: '白山千丈温泉セイモアスキー場', prefecture_id: '17')
Gerende.create(name: '大倉岳高原スキー場', prefecture_id: '17')
Gerende.create(name: '七尾コロサスキー場', prefecture_id: '17')
Gerende.create(name: '金沢市営医王山スキー場', prefecture_id: '17')
Gerende.create(name: 'スキージャム勝山', prefecture_id: '18')
Gerende.create(name: '今庄３６５スキー場', prefecture_id: '18')
Gerende.create(name: '福井和泉スキー場', prefecture_id: '18')
Gerende.create(name: '九頭竜スキー場', prefecture_id: '18')
Gerende.create(name: '新保ファミリースキー場', prefecture_id: '18')
Gerende.create(name: '六呂師高原スキーパーク', prefecture_id: '18')
Gerende.create(name: 'ふじてんスノーリゾート', prefecture_id: '19')
Gerende.create(name: 'サンメドウズ清里スキー場', prefecture_id: '19')
Gerende.create(name: 'カムイみさかスキー場', prefecture_id: '19')
Gerende.create(name: '白樺湖ロイヤルヒル', prefecture_id: '20')
Gerende.create(name: '白馬さのさかスキー場', prefecture_id: '20')
Gerende.create(name: '竜王スキーパーク', prefecture_id: '20')
Gerende.create(name: 'REWILD NINJA SNOW HIGHLAND', prefecture_id: '20')
Gerende.create(name: '栂池高原スキー場', prefecture_id: '20')
Gerende.create(name: '車山高原SKYPARKスキー場', prefecture_id: '20')
Gerende.create(name: '軽井沢プリンスホテルスキー場', prefecture_id: '20')
Gerende.create(name: '富士見パノラマリゾート', prefecture_id: '20')
Gerende.create(name: '佐久スキーガーデン「パラダ」北パラダスキー場', prefecture_id: '20')
Gerende.create(name: 'エイブル白馬五竜', prefecture_id: '20')
Gerende.create(name: '白馬コルチナスキー場', prefecture_id: '20')
Gerende.create(name: 'タングラムスキーサーカス', prefecture_id: '20')
Gerende.create(name: '菅平高原スノーリゾート', prefecture_id: '20')
Gerende.create(name: '中央道　伊那スキーリゾート', prefecture_id: '20')
Gerende.create(name: '志賀高原　焼額山スキー場', prefecture_id: '20')
Gerende.create(name: '斑尾高原スキー場', prefecture_id: '20')
Gerende.create(name: 'ブランシュたかやまスキーリゾート', prefecture_id: '20')
Gerende.create(name: 'ヘブンスそのはらSNOW WORLD', prefecture_id: '20')
Gerende.create(name: '奥志賀高原スキー場', prefecture_id: '20')
Gerende.create(name: 'シャトレーゼスキーリゾート八ヶ岳', prefecture_id: '20')
Gerende.create(name: 'Hakuba47 ウィンタースポーツぱーく', prefecture_id: '20')
Gerende.create(name: '信州松本　野麦峠スキー場', prefecture_id: '20')
Gerende.create(name: '湯の丸スキー場', prefecture_id: '20')
Gerende.create(name: '小海リエックス・スキーバレー', prefecture_id: '20')
Gerende.create(name: 'Mt.KOSHA よませ温泉スキー場　＆　X-JAM 高井富士', prefecture_id: '20')
Gerende.create(name: '八千穂高原スキー場', prefecture_id: '20')
Gerende.create(name: 'アサマ２０００パークいいづなリゾートスキー場', prefecture_id: '20')
Gerende.create(name: '白馬岩岳スノーフィールド', prefecture_id: '20')
Gerende.create(name: '富士見高原スキー場', prefecture_id: '20')
Gerende.create(name: '白馬八方尾根スキー場', prefecture_id: '20')
Gerende.create(name: '開田高原マイアスキー場', prefecture_id: '20')
Gerende.create(name: '治部坂高原スキー場', prefecture_id: '20')
Gerende.create(name: '野沢温泉スキー場', prefecture_id: '20')
Gerende.create(name: 'やぶはら高原スキー場', prefecture_id: '20')
Gerende.create(name: '戸狩温泉スキー場', prefecture_id: '20')
Gerende.create(name: 'Mt. 乗鞍スノーリゾート', prefecture_id: '20')
Gerende.create(name: '志賀高原　熊の湯スキー場', prefecture_id: '20')
Gerende.create(name: 'HAKUBAVALLEY 鹿島檜スキー場', prefecture_id: '20')
Gerende.create(name: '志賀高原リゾート中央エリア（サンバレー〜一の瀬）', prefecture_id: '20')
Gerende.create(name: '戸隠スキー場', prefecture_id: '20')
Gerende.create(name: '白馬乗鞍温泉スキー場', prefecture_id: '20')
Gerende.create(name: '北信州木島平スキー場', prefecture_id: '20')
Gerende.create(name: '爺ガ岳スキー場', prefecture_id: '20')
Gerende.create(name: '駒ヶ根高原スキー場', prefecture_id: '20')
Gerende.create(name: 'エコーバレースキー場', prefecture_id: '20')
Gerende.create(name: '聖高原スキー場', prefecture_id: '20')
Gerende.create(name: '佐久スキーガーデン「パラダ」南パラダスキー場', prefecture_id: '20')
Gerende.create(name: 'ファミリーゲレンデ　霧ヶ峰スキー場', prefecture_id: '20')
Gerende.create(name: '木曽福島スキー場', prefecture_id: '20')
Gerende.create(name: '蓼科東急スキー場', prefecture_id: '20')
Gerende.create(name: 'ひらや高原スキー場', prefecture_id: '20')
Gerende.create(name: '菅平パインビークスキー場', prefecture_id: '20')
Gerende.create(name: 'しらかば2in1スキー場', prefecture_id: '20')
Gerende.create(name: '白樺高原国際スキー場', prefecture_id: '20')
Gerende.create(name: 'ピラタス蓼科スノーリゾート', prefecture_id: '20')
Gerende.create(name: 'あさひプライムスキー場', prefecture_id: '20')
Gerende.create(name: '横手山・渋峠スキー場', prefecture_id: '20')
Gerende.create(name: '中央アルプス千畳敷スキー場', prefecture_id: '20')
Gerende.create(name: '黒姫高原スノーパーク', prefecture_id: '20')
Gerende.create(name: 'YAMABOKO ワイルドスノーパーク', prefecture_id: '20')
Gerende.create(name: 'Ontake2240', prefecture_id: '20')
Gerende.create(name: '武石番所ヶ原スキー場', prefecture_id: '20')
Gerende.create(name: '池の平スノーパーク', prefecture_id: '20')
Gerende.create(name: 'さかえ倶楽部スキー場', prefecture_id: '20')
Gerende.create(name: '飯綱高原スキー場', prefecture_id: '20')
Gerende.create(name: '北志賀高原小丸山スキー場', prefecture_id: '20')
Gerende.create(name: '山田温泉キッズスノーパーク', prefecture_id: '20')
Gerende.create(name: '鷲ヶ岳スキー場', prefecture_id: '21')
Gerende.create(name: 'ダイナランド', prefecture_id: '21')
Gerende.create(name: '高鷲スノーパーク', prefecture_id: '21')
Gerende.create(name: 'めいほうスキー場', prefecture_id: '21')
Gerende.create(name: 'スノーウェーブパーク白鳥高原', prefecture_id: '21')
Gerende.create(name: 'ウイングヒルズ白鳥リゾート', prefecture_id: '21')
Gerende.create(name: 'モンデウス飛騨位山スノーパーク', prefecture_id: '21')
Gerende.create(name: 'ホワイトピアたかす', prefecture_id: '21')
Gerende.create(name: 'ひるがの高原スキー場', prefecture_id: '21')
Gerende.create(name: '飛騨ほおきの平スキー場', prefecture_id: '21')
Gerende.create(name: 'ひだ舟山スノーリゾート　アルコピア', prefecture_id: '21')
Gerende.create(name: '平湯温泉スキー場', prefecture_id: '21')
Gerende.create(name: 'スノーヴァ羽島', prefecture_id: '21')
Gerende.create(name: '荘川高原スキー場', prefecture_id: '21')
Gerende.create(name: '飛騨かわいスキー場', prefecture_id: '21')
Gerende.create(name: '飛騨高山スキー場', prefecture_id: '21')
Gerende.create(name: 'しらおスキー場', prefecture_id: '21')
Gerende.create(name: '揖斐高原スキー場', prefecture_id: '21')
Gerende.create(name: 'スターシュプール緑風リゾートひだ流葉', prefecture_id: '21')
Gerende.create(name: 'アウトドアインもたいスキー場', prefecture_id: '21')
Gerende.create(name: '国見岳スキー場', prefecture_id: '21')
Gerende.create(name: '郡上高原スキー場', prefecture_id: '21')
Gerende.create(name: '白川郷平瀬温泉白弓スキー場', prefecture_id: '21')
Gerende.create(name: 'フジヤマ　スノーリゾート　イエティ', prefecture_id: '22')
Gerende.create(name: 'リバウェル井川スキー場', prefecture_id: '22')
Gerende.create(name: '大久保グラススキー場', prefecture_id: '22')
Gerende.create(name: '茶臼山高原スキー場', prefecture_id: '23')
Gerende.create(name: '御在所スキー場', prefecture_id: '24')
Gerende.create(name: 'グランスノー奥伊吹', prefecture_id: '25')
Gerende.create(name: 'びわ湖バレイ', prefecture_id: '25')
Gerende.create(name: '国境高原スノーパーク', prefecture_id: '25')
Gerende.create(name: '余呉高原リゾート・ヤップ', prefecture_id: '25')
Gerende.create(name: '箱館山スキー場', prefecture_id: '25')
Gerende.create(name: '朽木スキー場', prefecture_id: '25')
Gerende.create(name: '赤子山スキー場', prefecture_id: '25')
Gerende.create(name: 'マキノ高原マキノスキー場', prefecture_id: '25')
Gerende.create(name: 'スイス村スキーリゾート', prefecture_id: '26')
Gerende.create(name: 'アップかんなべ', prefecture_id: '28')
Gerende.create(name: '神鍋高原　万湯スキー場', prefecture_id: '28')
Gerende.create(name: '氷ノ山国際スキー場', prefecture_id: '28')
Gerende.create(name: '峰山高原リゾート', prefecture_id: '28')
Gerende.create(name: '奥神鍋スキー場', prefecture_id: '28')
Gerende.create(name: 'おじろスキー場', prefecture_id: '28')
Gerende.create(name: 'ちくさ高原スキー場', prefecture_id: '28')
Gerende.create(name: '若林高原おおやスキー場', prefecture_id: '28')
Gerende.create(name: 'ハチ・ハチ北スキー場', prefecture_id: '28')
Gerende.create(name: 'ばんしゅう戸倉スキー場', prefecture_id: '28')
Gerende.create(name: 'スカイバレイスキー場', prefecture_id: '28')
Gerende.create(name: '但馬牧場公園スキー場', prefecture_id: '28')
Gerende.create(name: 'ハイパーボウル東鉢', prefecture_id: '28')
Gerende.create(name: 'ミカタスノーパーク', prefecture_id: '28')
Gerende.create(name: '六甲山スノーパーク', prefecture_id: '28')
Gerende.create(name: 'スノーパーク洞川', prefecture_id: '29')
Gerende.create(name: '大山鏡ヶ成スキー場', prefecture_id: '31')
Gerende.create(name: 'だいせんホワイトリゾート', prefecture_id: '31')
Gerende.create(name: '大山ますみず高原スキー場　SNOW PARK', prefecture_id: '31')
Gerende.create(name: '奥大山スキー場', prefecture_id: '31')
Gerende.create(name: 'わかさ氷ノ山スキー場', prefecture_id: '31')
Gerende.create(name: '琴引フォレストパーク', prefecture_id: '32')
Gerende.create(name: 'アサヒテングストン', prefecture_id: '32')
Gerende.create(name: '三井野原スキー場', prefecture_id: '32')
Gerende.create(name: 'ひるぜんベアバレースキー場', prefecture_id: '33')
Gerende.create(name: '津黒高原スキー場', prefecture_id: '33')
Gerende.create(name: 'いぶきの里スキー場', prefecture_id: '33')
Gerende.create(name: 'ひるぜんキッズスノーパーク', prefecture_id: '33')
Gerende.create(name: '恩原高原スキー場', prefecture_id: '33')
Gerende.create(name: '大芽スキー場', prefecture_id: '33')
Gerende.create(name: 'スノーリゾート猫山', prefecture_id: '34')
Gerende.create(name: '恐羅漢スノーパーク', prefecture_id: '34')
Gerende.create(name: '女鹿平温泉めがひらスキー場', prefecture_id: '34')
Gerende.create(name: '芸北国際スキー場', prefecture_id: '34')
Gerende.create(name: 'やわたハイランド191リゾート', prefecture_id: '34')
Gerende.create(name: 'ひろしま県民の森スキー場', prefecture_id: '34')
Gerende.create(name: 'ユートピアサイオト', prefecture_id: '34')
Gerende.create(name: '大佐スキー場', prefecture_id: '34')
Gerende.create(name: 'もみのき森林公園スキー場', prefecture_id: '34')
Gerende.create(name: 'りんご今日話国スキー場', prefecture_id: '34')
Gerende.create(name: '道後山高原スキー場', prefecture_id: '34')
Gerende.create(name: '十種ヶ峰スキー場', prefecture_id: '35')
Gerende.create(name: '井川スキー場　腕山', prefecture_id: '36')
Gerende.create(name: '石鎚スキー場', prefecture_id: '38')
Gerende.create(name: '久万スキーランド', prefecture_id: '38')
Gerende.create(name: 'SOL-FA オダスキーゲレンデ', prefecture_id: '38')
Gerende.create(name: '天狗高原スキー場', prefecture_id: '39')
Gerende.create(name: '天山スキー場', prefecture_id: '41')
Gerende.create(name: '九重スキー場', prefecture_id: '10')