Gerende.create(name: 'ルスツリゾート(北海道)', prefecture_id: '1', image: "https://rusutsu.com/wp-content/uploads/trail-map-winter.jpg")
Gerende.create(name: '富良野スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '星野リゾート　トマム　スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '函館七飯スノーパーク(北海道)', prefecture_id: '1')
Gerende.create(name: 'ニセコマウンテンリゾート　グラン・ヒラフ(北海道)', prefecture_id: '1')
Gerende.create(name: 'ニセコHANZONOリゾート(北海道)', prefecture_id: '1')
Gerende.create(name: 'サッポロテイネ(北海道)', prefecture_id: '1')
Gerende.create(name: 'KIRORO SNOW WORLD(北海道)', prefecture_id: '1')
Gerende.create(name: '札幌町民スキー場　びゅー(北海道)', prefecture_id: '1')
Gerende.create(name: '中頓別寿スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '札幌藻岩山スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: 'サンタプレゼントパーク　マロースゲレンデ(北海道)', prefecture_id: '1')
Gerende.create(name: 'ニセコモイワスキーリゾート(北海道)', prefecture_id: '1')
Gerende.create(name: '三笠桂沢国設スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: 'ニセコアンヌプリ国際スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: 'サホロリゾートスキー場(北海道)', prefecture_id: '1')
Gerende.create(name: 'カムイスキーリンクス(北海道)', prefecture_id: '1')
Gerende.create(name: '北見市留辺蘂町　八方大スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '和寒町東山スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '大雪山　黒岳スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: 'セコビレッジスキーリゾート(北海道)', prefecture_id: '1')
Gerende.create(name: 'マウントレースイスキーリゾート(北海道)', prefecture_id: '1')
Gerende.create(name: 'キャンモアスキービレッジ(北海道)', prefecture_id: '1')
Gerende.create(name: 'さっぽろばんけいスキー場(北海道)', prefecture_id: '1')
Gerende.create(name: 'ぴっぷスキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '国設芦別スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '置戸町南ヶ丘スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '小樽天狗山スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: 'ウィンザースノービレッジ(北海道)', prefecture_id: '1')
Gerende.create(name: '中山峠スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: 'SNOW CRUISE ONZE(北海道)', prefecture_id: '1')
Gerende.create(name: 'ダイナスティスキーリゾート(北海道)', prefecture_id: '1')
Gerende.create(name: '朝里川温泉スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '今金町ピリカスキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '札幌国際スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '名寄ピヤシリスキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '豊富温泉スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '士別市　日向スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '士別市あさひスキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '沼田町営高穂スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '暑寒別岳スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '中富良野北星スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '幌延町東ヶ丘スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '上川町営中山スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '稚内市こまどりスキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '枝幸町三笠山スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: 'とうま山スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '安平山スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '忠類白銀台スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '明野ヶ丘スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '佐呂間町営スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '北見若松市民スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '標津町営金山スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: 'メムロスキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '紋別市営大山スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '清里町営緑スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: 'IWANAI RESORT(北海道)', prefecture_id: '1')
Gerende.create(name: 'Fu’s snow area(北海道)', prefecture_id: '1')
Gerende.create(name: 'ほろたちスキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '美唄国設スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '岩見沢萩の山市民スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '長沼スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '日高国際スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '仁木町民スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: 'オロフレスキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '倶知安町旭ヶ丘スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: 'そっち岳スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: 'ニヤマ高原スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '石狩平原スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: 'カルルス温泉サンライバスキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '国設南ふらのスキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '国設阿寒湖畔スキー場「ウタラ」(北海道)', prefecture_id: '1')
Gerende.create(name: 'ぬかびら源泉郷スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '音威富士スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: 'グリーンピア大沼スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '湧別町　五鹿山スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '滝野スノーワールド(北海道)', prefecture_id: '1')
Gerende.create(name: 'かもい岳スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '阿寒ロイヤルバレイスキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '網走レークビュースキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '伊ノ沢市民スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: 'んがるロックバレースキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '部町営スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '小平町望洋台スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '富良野町日の出スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '斜里町ウナベツスキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '知内町営スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '新得山スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '滝上町桜ヶ丘スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: 'チセヌプリスキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '天塩町町民スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '美深スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '美幌町リリー山スキー場(北海道)', prefecture_id: '1')
Gerende.create(name: '北海法グリーンランドホワイトパーク(北海道)', prefecture_id: '1')
Gerende.create(name: '室蘭市高原だんパラスキー場 (北海道)', prefecture_id: '1')
Gerende.create(name: '青森スプリング・スキーリゾート(青森)', prefecture_id: '2')
Gerende.create(name: '創遊村229スキーランド(青森)', prefecture_id: '2')
Gerende.create(name: 'まかど温泉スキー場(青森)', prefecture_id: '2')
Gerende.create(name: '大鰐温泉スキー場(青森)', prefecture_id: '2')
Gerende.create(name: '八甲田スキー場(青森)', prefecture_id: '2')
Gerende.create(name: 'むつ市釜臥山スキー場(青森)', prefecture_id: '2')
Gerende.create(name: '十和田湖温泉スキー場(青森)', prefecture_id: '2')
Gerende.create(name: 'そうまロマントピアスキー場(青森)', prefecture_id: '2')
Gerende.create(name: '岩木山百沢スキー場(青森)', prefecture_id: '2')
Gerende.create(name: '七戸町営スキー場(青森)', prefecture_id: '2')
Gerende.create(name: 'モヤヒルズ(青森)', prefecture_id: '2')
Gerende.create(name: '夜越山スキー場(青森)', prefecture_id: '2')
Gerende.create(name: '安比高原スキー場(岩手)', prefecture_id: '3')
Gerende.create(name: '夏油高原スキー場(岩手)', prefecture_id: '3')
Gerende.create(name: '岩手高原スノーパーク(岩手)', prefecture_id: '3')
Gerende.create(name: '雫石スキー場(岩手)', prefecture_id: '3')
Gerende.create(name: '八幡平リゾート　パノラマスキー場＆下倉スキー場(岩手)', prefecture_id: '3')
Gerende.create(name: '奥中山高原スキー場(岩手)', prefecture_id: '3')
Gerende.create(name: 'ひめゆかスキー場(岩手)', prefecture_id: '3')
Gerende.create(name: '網張温泉スキー場(岩手)', prefecture_id: '3')
Gerende.create(name: '八幡平市　田山スキー場(岩手)', prefecture_id: '3')
Gerende.create(name: '町営湯田スキー場(岩手)', prefecture_id: '3')
Gerende.create(name: '平庭高原スキー場(岩手)', prefecture_id: '3')
Gerende.create(name: '国見平スキー場(岩手)', prefecture_id: '3')
Gerende.create(name: '奥州市越路スキー場(岩手)', prefecture_id: '3')
Gerende.create(name: '赤羽根スキー場(岩手)', prefecture_id: '3')
Gerende.create(name: 'くのへスキー場(岩手)', prefecture_id: '3')
Gerende.create(name: '花巻市鉛温泉スキー場(岩手)', prefecture_id: '3')
Gerende.create(name: 'スプリングバレー仙台泉スキー場(宮城)', prefecture_id: '4')
Gerende.create(name: 'オニコウベスキー場(宮城)', prefecture_id: '4')
Gerende.create(name: 'みやぎ蔵王えぼしリゾート(宮城)', prefecture_id: '4')
Gerende.create(name: 'みやぎ蔵王白石スキー場(宮城)', prefecture_id: '4')
Gerende.create(name: 'みやぎ蔵王七ヶ宿スキー場(宮城)', prefecture_id: '4')
Gerende.create(name: '泉ヶ岳スキー場(宮城)', prefecture_id: '4')
Gerende.create(name: 'やくらいファミリースキー場(宮城)', prefecture_id: '4')
Gerende.create(name: 'みやぎ蔵王スキー場　すみかわスノーパーク(宮城)', prefecture_id: '4')
Gerende.create(name: 'みやぎ蔵王セントメリースキー場(宮城)', prefecture_id: '4')
Gerende.create(name: '上野々スキー場(宮城)', prefecture_id: '4')
Gerende.create(name: '鳥海高原矢島スキー場(秋田)', prefecture_id: '5')
Gerende.create(name: '水晶山スキー場(秋田)', prefecture_id: '5')
Gerende.create(name: '秋田八幡平スキー場(秋田)', prefecture_id: '5')
Gerende.create(name: '太平山スキー場　オーパス(秋田)', prefecture_id: '5')
Gerende.create(name: 'たざわ湖スキー場(秋田)', prefecture_id: '5')
Gerende.create(name: '大仙市営協和スキー場(秋田)', prefecture_id: '5')
Gerende.create(name: '藤里町営スキー場(秋田)', prefecture_id: '5')
Gerende.create(name: '稲川スキー場(秋田)', prefecture_id: '5')
Gerende.create(name: '花輪スキー場(秋田)', prefecture_id: '5')
Gerende.create(name: '大仙市営大曲ファミリースキー場(秋田)', prefecture_id: '5')
Gerende.create(name: '大仙市営大台スキー場(秋田)', prefecture_id: '5')
Gerende.create(name: 'ジュネス栗駒スキー場(秋田)', prefecture_id: '5')
Gerende.create(name: '阿仁スキー場(秋田)', prefecture_id: '5')
Gerende.create(name: '横手市天下森スキー場(秋田)', prefecture_id: '5')
Gerende.create(name: '黒伏高原スノーパーク　ジャングル・ジャングル(山形)', prefecture_id: '6')
Gerende.create(name: '天元台高原(山形)', prefecture_id: '6')
Gerende.create(name: '蔵王温泉スキー場(山形)', prefecture_id: '6')
Gerende.create(name: 'グリーンバレー神室スキー場(山形)', prefecture_id: '6')
Gerende.create(name: '天童高原スキー場(山形)', prefecture_id: '6')
Gerende.create(name: 'Asahi自然観　SNOW PARK(山形)', prefecture_id: '6')
Gerende.create(name: '湯殿山スキー場(山形)', prefecture_id: '6')
Gerende.create(name: '蔵王ライザワールド(山形)', prefecture_id: '6')
Gerende.create(name: '羽黒山スキー場(山形)', prefecture_id: '6')
Gerende.create(name: '白鷹町営スキー場(山形)', prefecture_id: '6')
Gerende.create(name: '蔵王猿倉スキー場(山形)', prefecture_id: '6')
Gerende.create(name: '月山スキー場(山形)', prefecture_id: '6')
Gerende.create(name: '米沢スキー場(山形)', prefecture_id: '6')
Gerende.create(name: 'やまがた　赤倉温泉スキー場(山形)', prefecture_id: '6')
Gerende.create(name: '新庄市民スキー場(山形)', prefecture_id: '6')
Gerende.create(name: '櫛引たらのきだいスキー場(山形)', prefecture_id: '6')
Gerende.create(name: '松山スキー場(山形)', prefecture_id: '6')
Gerende.create(name: '西川町民スキー場(山形)', prefecture_id: '6')
Gerende.create(name: '小国町横根スキー場(山形)', prefecture_id: '6')
Gerende.create(name: '小野川温泉スキー場(山形)', prefecture_id: '6')
Gerende.create(name: '手ノ子スキー場(山形)', prefecture_id: '6')
Gerende.create(name: '花笠高原スキー場(山形)', prefecture_id: '6')
Gerende.create(name: 'グランデコスノーリゾート(福島)', prefecture_id: '7')
Gerende.create(name: '猪苗代スキー場(福島)', prefecture_id: '7')
Gerende.create(name: '箕輪スキー場(福島)', prefecture_id: '7')
Gerende.create(name: '会津高原たかつえスキー場(福島)', prefecture_id: '7')
Gerende.create(name: '会津高原高畑スキー場(福島)', prefecture_id: '7')
Gerende.create(name: 'グランディ羽鳥湖スキーリゾート(福島)', prefecture_id: '7')
Gerende.create(name: '会津高原だいくらスキー場(福島)', prefecture_id: '7')
Gerende.create(name: '星野リゾート　猫魔スキー場(福島)', prefecture_id: '7')
Gerende.create(name: '星野リゾート　アルツ磐梯(福島)', prefecture_id: '7')
Gerende.create(name: '会津高原南郷スキー場(福島)', prefecture_id: '7')
Gerende.create(name: '尾瀬檜枝岐温泉スキー場(福島)', prefecture_id: '7')
Gerende.create(name: '沼尻スキー場(福島)', prefecture_id: '7')
Gerende.create(name: 'あただら高原スキー場(福島)', prefecture_id: '7')
Gerende.create(name: 'リステルスキーファンタジア(福島)', prefecture_id: '7')
Gerende.create(name: 'ファミリースノーパーク　ばんだい×２(福島)', prefecture_id: '7')
Gerende.create(name: '猪苗代リゾートスキー(福島)', prefecture_id: '7')
Gerende.create(name: '裏磐梯スキー場(福島)', prefecture_id: '7')
Gerende.create(name: '二本松塩沢スキー場(福島)', prefecture_id: '7')
Gerende.create(name: '喜多方市三ノ倉スキー場(福島)', prefecture_id: '7')
Gerende.create(name: 'スキーリゾート天栄(福島)', prefecture_id: '7')
Gerende.create(name: '只見スキー場(福島)', prefecture_id: '7')
Gerende.create(name: 'フェアリーランドかねやまスキー場(福島)', prefecture_id: '7')
Gerende.create(name: '横向温泉スキー場(福島)', prefecture_id: '7')
Gerende.create(name: 'ハンターマウンテン塩原(栃木)', prefecture_id: '9')
Gerende.create(name: 'マウントジーンズ那須(栃木)', prefecture_id: '9')
Gerende.create(name: '日光湯元温泉スキー場(栃木)', prefecture_id: '9')
Gerende.create(name: 'エーデルワイススキー場(栃木)', prefecture_id: '9')
Gerende.create(name: '那須温泉ファミリースキー場(栃木)', prefecture_id: '9')
Gerende.create(name: '奥利根スノーパーク(群馬)', prefecture_id: '10')
Gerende.create(name: 'たんばらスキーパーク(群馬)', prefecture_id: '10')
Gerende.create(name: 'ノルン水上スキー場(群馬)', prefecture_id: '10')
Gerende.create(name: 'ホワイトワールド尾瀬岩鞍(群馬)', prefecture_id: '10')
Gerende.create(name: '川場スキー場(群馬)', prefecture_id: '10')
Gerende.create(name: '水上高原スキーリゾート(群馬)', prefecture_id: '10')
Gerende.create(name: '軽井沢スノーパーク(群馬)', prefecture_id: '10')
Gerende.create(name: '水上宝台樹スキー場(群馬)', prefecture_id: '10')
Gerende.create(name: 'パルコールつま恋スキーリゾート(群馬)', prefecture_id: '10')
Gerende.create(name: '丸沼高原スキー場(群馬)', prefecture_id: '10')
Gerende.create(name: '水上高原・奥利根温泉　藤原スキー場(群馬)', prefecture_id: '10')
Gerende.create(name: '万座温泉スキー場(群馬)', prefecture_id: '10')
Gerende.create(name: 'かたしな高原スキー場(群馬)', prefecture_id: '10')
Gerende.create(name: '草津温泉スキー場(群馬)', prefecture_id: '10')
Gerende.create(name: 'ホワイトバレースキー場(群馬)', prefecture_id: '10')
Gerende.create(name: 'オグナほたかスキー場スノーパーク尾瀬戸倉(群馬)', prefecture_id: '10')
Gerende.create(name: '鹿沢スノーエリア(群馬)', prefecture_id: '10')
Gerende.create(name: 'みなかみ町営赤沢スキー場(群馬)', prefecture_id: '10')
Gerende.create(name: 'ホテルヴィレッジ森のスキー場(群馬)', prefecture_id: '10')
Gerende.create(name: '赤城山　第一スキー場(群馬)', prefecture_id: '10')
Gerende.create(name: '谷川岳天神平スキー場(群馬)', prefecture_id: '10')
Gerende.create(name: '狭山スキー場(埼玉)', prefecture_id: '11')
Gerende.create(name: 'スノーヴァ新横浜(神奈川)', prefecture_id: '14')
Gerende.create(name: '赤倉温泉スキー場(新潟)', prefecture_id: '15')
Gerende.create(name: '舞子スノーリゾート(新潟)', prefecture_id: '15')
Gerende.create(name: 'キューピットバレイ(新潟)', prefecture_id: '15')
Gerende.create(name: 'ムイカスノーリゾート(新潟)', prefecture_id: '15')
Gerende.create(name: 'ロッテアライリゾート(新潟)', prefecture_id: '15')
Gerende.create(name: '湯沢中里スノーリゾート(新潟)', prefecture_id: '15')
Gerende.create(name: '苗場スキー上(新潟)', prefecture_id: '15')
Gerende.create(name: '神立スノーリゾート(新潟)', prefecture_id: '15')
Gerende.create(name: '上越国際スキー場(新潟)', prefecture_id: '15')
Gerende.create(name: '妙高杉ノ原スキー場(新潟)', prefecture_id: '15')
Gerende.create(name: 'NASPAスキーガーデン(新潟)', prefecture_id: '15')
Gerende.create(name: '湯沢パークスキー場(新潟)', prefecture_id: '15')
Gerende.create(name: 'かぐらスキー場(新潟)', prefecture_id: '15')
Gerende.create(name: '湯沢高原スキー場(新潟)', prefecture_id: '15')
Gerende.create(name: 'GALA湯沢スキー場(新潟)', prefecture_id: '15')
Gerende.create(name: '石打丸山スキー場(新潟)', prefecture_id: '15')
Gerende.create(name: 'シャルマン火打スキー場(新潟)', prefecture_id: '15')
Gerende.create(name: '六日町八海山スキー場(新潟)', prefecture_id: '15')
Gerende.create(name: '奥只見丸山スキー場(新潟)', prefecture_id: '15')
Gerende.create(name: 'ニュー・グリーンピア津南スキー場(新潟)', prefecture_id: '15')
Gerende.create(name: '岩原スキー場(新潟)', prefecture_id: '15')
Gerende.create(name: '須原スキー場(新潟)', prefecture_id: '15')
Gerende.create(name: '池の平温泉スキー場(新潟)', prefecture_id: '15')
Gerende.create(name: 'ニノックススノーパーク(新潟)', prefecture_id: '15')
Gerende.create(name: '赤倉観光リゾートスキー場(新潟)', prefecture_id: '15')
Gerende.create(name: '小出スキー場(新潟)', prefecture_id: '15')
Gerende.create(name: '三川・温泉スキー場(新潟)', prefecture_id: '15')
Gerende.create(name: '松之山温泉スキー場(新潟)', prefecture_id: '15')
Gerende.create(name: 'とちおファミリースキー場(新潟)', prefecture_id: '15')
Gerende.create(name: '松代ファミリースキー場(新潟)', prefecture_id: '15')
Gerende.create(name: '湯沢一本杉スキー場(新潟)', prefecture_id: '15')
Gerende.create(name: '糸魚川シーサイドバレースキー場(新潟)', prefecture_id: '15')
Gerende.create(name: '休暇村妙高　ルンルンスキー場(新潟)', prefecture_id: '15')
Gerende.create(name: '高柳ガルルのスキー場(新潟)', prefecture_id: '15')
Gerende.create(name: '八海山麓スキー場(新潟)', prefecture_id: '15')
Gerende.create(name: 'シャトー塩沢(新潟)', prefecture_id: '15')
Gerende.create(name: 'なかさと清津スキー場(新潟)', prefecture_id: '15')
Gerende.create(name: '魚沼大原スキー場(新潟)', prefecture_id: '15')
Gerende.create(name: '石打花岡スキー場(新潟)', prefecture_id: '15')
Gerende.create(name: '金谷山スキー場(新潟)', prefecture_id: '15')
Gerende.create(name: '関温泉スキー場(新潟)', prefecture_id: '15')
Gerende.create(name: '胎内スキー場(新潟)', prefecture_id: '15')
Gerende.create(name: '薬師スキー場(新潟)', prefecture_id: '15')
Gerende.create(name: '長岡市営スキー場(新潟)', prefecture_id: '15')
Gerende.create(name: 'わぶかな高原スキー場(新潟)', prefecture_id: '15')
Gerende.create(name: '大湯温泉スキー場(新潟)', prefecture_id: '15')
Gerende.create(name: '村上市　ぶどうスキー場(新潟)', prefecture_id: '15')
Gerende.create(name: '妙高スキーパーク(新潟)', prefecture_id: '15')
Gerende.create(name: '五日町スキー場(新潟)', prefecture_id: '15')
Gerende.create(name: '古志高原スキー場(新潟)', prefecture_id: '15')
Gerende.create(name: '中里スノーウッドスキー場(新潟)', prefecture_id: '15')
Gerende.create(name: 'Mt.グランビュー(新潟)', prefecture_id: '15')
Gerende.create(name: '牛岳温泉スキー場(富山)', prefecture_id: '16')
Gerende.create(name: 'たいらスキー場(富山)', prefecture_id: '16')
Gerende.create(name: 'となみ夢の平スキー場(富山)', prefecture_id: '16')
Gerende.create(name: 'IOXーAROSA(富山)', prefecture_id: '16')
Gerende.create(name: '立山山麓スキー場(富山)', prefecture_id: '16')
Gerende.create(name: 'タカンボースキー場(富山)', prefecture_id: '16')
Gerende.create(name: '宇奈月温泉スキー場(富山)', prefecture_id: '16')
Gerende.create(name: '白山一里野温泉スキー場(石川)', prefecture_id: '17')
Gerende.create(name: '白山千丈温泉セイモアスキー場(石川)', prefecture_id: '17')
Gerende.create(name: '大倉岳高原スキー場(石川)', prefecture_id: '17')
Gerende.create(name: '七尾コロサスキー場(石川)', prefecture_id: '17')
Gerende.create(name: '金沢市営医王山スキー場(石川)', prefecture_id: '17')
Gerende.create(name: 'スキージャム勝山(福井)', prefecture_id: '18')
Gerende.create(name: '今庄３６５スキー場(福井)', prefecture_id: '18')
Gerende.create(name: '福井和泉スキー場(福井)', prefecture_id: '18')
Gerende.create(name: '九頭竜スキー場(福井)', prefecture_id: '18')
Gerende.create(name: '新保ファミリースキー場(福井)', prefecture_id: '18')
Gerende.create(name: '六呂師高原スキーパーク(福井)', prefecture_id: '18')
Gerende.create(name: 'ふじてんスノーリゾート(山梨)', prefecture_id: '19')
Gerende.create(name: 'サンメドウズ清里スキー場(山梨)', prefecture_id: '19')
Gerende.create(name: 'カムイみさかスキー場(山梨)', prefecture_id: '19')
Gerende.create(name: '白樺湖ロイヤルヒル(長野)', prefecture_id: '20')
Gerende.create(name: '白馬さのさかスキー場(長野)', prefecture_id: '20')
Gerende.create(name: '竜王スキーパーク(長野)', prefecture_id: '20')
Gerende.create(name: 'REWILD NINJA SNOW HIGHLAND(長野)', prefecture_id: '20')
Gerende.create(name: '栂池高原スキー場(長野)', prefecture_id: '20')
Gerende.create(name: '車山高原SKYPARKスキー場(長野)', prefecture_id: '20')
Gerende.create(name: '軽井沢プリンスホテルスキー場(長野)', prefecture_id: '20')
Gerende.create(name: '富士見パノラマリゾート(長野)', prefecture_id: '20')
Gerende.create(name: '佐久スキーガーデン「パラダ」北パラダスキー場(長野)', prefecture_id: '20')
Gerende.create(name: 'エイブル白馬五竜(長野)', prefecture_id: '20')
Gerende.create(name: '白馬コルチナスキー場(長野)', prefecture_id: '20')
Gerende.create(name: 'タングラムスキーサーカス(長野)', prefecture_id: '20')
Gerende.create(name: '菅平高原スノーリゾート(長野)', prefecture_id: '20')
Gerende.create(name: '中央道　伊那スキーリゾート(長野)', prefecture_id: '20')
Gerende.create(name: '志賀高原　焼額山スキー場(長野)', prefecture_id: '20')
Gerende.create(name: '斑尾高原スキー場(長野)', prefecture_id: '20')
Gerende.create(name: 'ブランシュたかやまスキーリゾート(長野)', prefecture_id: '20')
Gerende.create(name: 'ヘブンスそのはらSNOW WORLD(長野)', prefecture_id: '20')
Gerende.create(name: '奥志賀高原スキー場(長野)', prefecture_id: '20')
Gerende.create(name: 'シャトレーゼスキーリゾート八ヶ岳(長野)', prefecture_id: '20')
Gerende.create(name: 'Hakuba47 ウィンタースポーツぱーく(長野)', prefecture_id: '20')
Gerende.create(name: '信州松本　野麦峠スキー場(長野)', prefecture_id: '20')
Gerende.create(name: '湯の丸スキー場(長野)', prefecture_id: '20')
Gerende.create(name: '小海リエックス・スキーバレー(長野)', prefecture_id: '20')
Gerende.create(name: 'Mt.KOSHA よませ温泉スキー場　＆　X-JAM 高井富士(長野)', prefecture_id: '20')
Gerende.create(name: '八千穂高原スキー場(長野)', prefecture_id: '20')
Gerende.create(name: 'アサマ２０００パークいいづなリゾートスキー場(長野)', prefecture_id: '20')
Gerende.create(name: '白馬岩岳スノーフィールド(長野)', prefecture_id: '20')
Gerende.create(name: '富士見高原スキー場(長野)', prefecture_id: '20')
Gerende.create(name: '白馬八方尾根スキー場(長野)', prefecture_id: '20')
Gerende.create(name: '開田高原マイアスキー場(長野)', prefecture_id: '20')
Gerende.create(name: '治部坂高原スキー場(長野)', prefecture_id: '20')
Gerende.create(name: '野沢温泉スキー場(長野)', prefecture_id: '20')
Gerende.create(name: 'やぶはら高原スキー場(長野)', prefecture_id: '20')
Gerende.create(name: '戸狩温泉スキー場(長野)', prefecture_id: '20')
Gerende.create(name: 'Mt. 乗鞍スノーリゾート(長野)', prefecture_id: '20')
Gerende.create(name: '志賀高原　熊の湯スキー場(長野)', prefecture_id: '20')
Gerende.create(name: 'HAKUBAVALLEY 鹿島檜スキー場(長野)', prefecture_id: '20')
Gerende.create(name: '志賀高原リゾート中央エリア（サンバレー〜一の瀬）(長野)', prefecture_id: '20')
Gerende.create(name: '戸隠スキー場(長野)', prefecture_id: '20')
Gerende.create(name: '白馬乗鞍温泉スキー場(長野)', prefecture_id: '20')
Gerende.create(name: '北信州木島平スキー場(長野)', prefecture_id: '20')
Gerende.create(name: '爺ガ岳スキー場(長野)', prefecture_id: '20')
Gerende.create(name: '駒ヶ根高原スキー場(長野)', prefecture_id: '20')
Gerende.create(name: 'エコーバレースキー場(長野)', prefecture_id: '20')
Gerende.create(name: '聖高原スキー場(長野)', prefecture_id: '20')
Gerende.create(name: '佐久スキーガーデン「パラダ」南パラダスキー場(長野)', prefecture_id: '20')
Gerende.create(name: 'ファミリーゲレンデ　霧ヶ峰スキー場(長野)', prefecture_id: '20')
Gerende.create(name: '木曽福島スキー場(長野)', prefecture_id: '20')
Gerende.create(name: '蓼科東急スキー場(長野)', prefecture_id: '20')
Gerende.create(name: 'ひらや高原スキー場(長野)', prefecture_id: '20')
Gerende.create(name: '菅平パインビークスキー場(長野)', prefecture_id: '20')
Gerende.create(name: 'しらかば2in1スキー場(長野)', prefecture_id: '20')
Gerende.create(name: '白樺高原国際スキー場(長野)', prefecture_id: '20')
Gerende.create(name: 'ピラタス蓼科スノーリゾート(長野)', prefecture_id: '20')
Gerende.create(name: 'あさひプライムスキー場(長野)', prefecture_id: '20')
Gerende.create(name: '横手山・渋峠スキー場(長野)', prefecture_id: '20')
Gerende.create(name: '中央アルプス千畳敷スキー場(長野)', prefecture_id: '20')
Gerende.create(name: '黒姫高原スノーパーク(長野)', prefecture_id: '20')
Gerende.create(name: 'YAMABOKO ワイルドスノーパーク(長野)', prefecture_id: '20')
Gerende.create(name: 'Ontake2240(長野)', prefecture_id: '20')
Gerende.create(name: '武石番所ヶ原スキー場(長野)', prefecture_id: '20')
Gerende.create(name: '池の平スノーパーク(長野)', prefecture_id: '20')
Gerende.create(name: 'さかえ倶楽部スキー場(長野)', prefecture_id: '20')
Gerende.create(name: '飯綱高原スキー場(長野)', prefecture_id: '20')
Gerende.create(name: '北志賀高原小丸山スキー場(長野)', prefecture_id: '20')
Gerende.create(name: '山田温泉キッズスノーパーク(長野)', prefecture_id: '20')
Gerende.create(name: '鷲ヶ岳スキー場(岐阜)', prefecture_id: '21')
Gerende.create(name: 'ダイナランド(岐阜)', prefecture_id: '21')
Gerende.create(name: '高鷲スノーパーク(岐阜)', prefecture_id: '21')
Gerende.create(name: 'めいほうスキー場(岐阜)', prefecture_id: '21')
Gerende.create(name: 'スノーウェーブパーク白鳥高原(岐阜)', prefecture_id: '21')
Gerende.create(name: 'ウイングヒルズ白鳥リゾート(岐阜)', prefecture_id: '21')
Gerende.create(name: 'モンデウス飛騨位山スノーパーク(岐阜)', prefecture_id: '21')
Gerende.create(name: 'ホワイトピアたかす(岐阜)', prefecture_id: '21')
Gerende.create(name: 'ひるがの高原スキー場(岐阜)', prefecture_id: '21')
Gerende.create(name: '飛騨ほおきの平スキー場(岐阜)', prefecture_id: '21')
Gerende.create(name: 'ひだ舟山スノーリゾート　アルコピア(岐阜)', prefecture_id: '21')
Gerende.create(name: '平湯温泉スキー場(岐阜)', prefecture_id: '21')
Gerende.create(name: 'スノーヴァ羽島(岐阜)', prefecture_id: '21')
Gerende.create(name: '荘川高原スキー場(岐阜)', prefecture_id: '21')
Gerende.create(name: '飛騨かわいスキー場(岐阜)', prefecture_id: '21')
Gerende.create(name: '飛騨高山スキー場(岐阜)', prefecture_id: '21')
Gerende.create(name: 'しらおスキー場(岐阜)', prefecture_id: '21')
Gerende.create(name: '揖斐高原スキー場(岐阜)', prefecture_id: '21')
Gerende.create(name: 'スターシュプール緑風リゾートひだ流葉(岐阜)', prefecture_id: '21')
Gerende.create(name: 'アウトドアインもたいスキー場(岐阜)', prefecture_id: '21')
Gerende.create(name: '国見岳スキー場(岐阜)', prefecture_id: '21')
Gerende.create(name: '郡上高原スキー場(岐阜)', prefecture_id: '21')
Gerende.create(name: '白川郷平瀬温泉白弓スキー場(岐阜)', prefecture_id: '21')
Gerende.create(name: 'フジヤマ　スノーリゾート　イエティ(静岡)', prefecture_id: '22')
Gerende.create(name: 'リバウェル井川スキー場(静岡)', prefecture_id: '22')
Gerende.create(name: '大久保グラススキー場(静岡)', prefecture_id: '22')
Gerende.create(name: '茶臼山高原スキー場(愛知)', prefecture_id: '23')
Gerende.create(name: '御在所スキー場(三重)', prefecture_id: '24')
Gerende.create(name: 'グランスノー奥伊吹(滋賀)', prefecture_id: '25')
Gerende.create(name: 'びわ湖バレイ(滋賀)', prefecture_id: '25')
Gerende.create(name: '国境高原スノーパーク(滋賀)', prefecture_id: '25')
Gerende.create(name: '余呉高原リゾート・ヤップ(滋賀)', prefecture_id: '25')
Gerende.create(name: '箱館山スキー場(滋賀)', prefecture_id: '25')
Gerende.create(name: '朽木スキー場(滋賀)', prefecture_id: '25')
Gerende.create(name: '赤子山スキー場(滋賀)', prefecture_id: '25')
Gerende.create(name: 'マキノ高原マキノスキー場(滋賀)', prefecture_id: '25')
Gerende.create(name: 'スイス村スキーリゾート(京都)', prefecture_id: '26')
Gerende.create(name: 'アップかんなべ(兵庫)', prefecture_id: '28')
Gerende.create(name: '神鍋高原　万湯スキー場(兵庫)', prefecture_id: '28')
Gerende.create(name: '氷ノ山国際スキー場(兵庫)', prefecture_id: '28')
Gerende.create(name: '峰山高原リゾート(兵庫)', prefecture_id: '28')
Gerende.create(name: '奥神鍋スキー場(兵庫)', prefecture_id: '28')
Gerende.create(name: 'おじろスキー場(兵庫)', prefecture_id: '28')
Gerende.create(name: 'ちくさ高原スキー場(兵庫)', prefecture_id: '28')
Gerende.create(name: '若林高原おおやスキー場(兵庫)', prefecture_id: '28')
Gerende.create(name: 'ハチ・ハチ北スキー場(兵庫)', prefecture_id: '28')
Gerende.create(name: 'ばんしゅう戸倉スキー場(兵庫)', prefecture_id: '28')
Gerende.create(name: 'スカイバレイスキー場(兵庫)', prefecture_id: '28')
Gerende.create(name: '但馬牧場公園スキー場(兵庫)', prefecture_id: '28')
Gerende.create(name: 'ハイパーボウル東鉢(兵庫)', prefecture_id: '28')
Gerende.create(name: 'ミカタスノーパーク(兵庫)', prefecture_id: '28')
Gerende.create(name: '六甲山スノーパーク(兵庫)', prefecture_id: '28')
Gerende.create(name: 'スノーパーク洞川(奈良)', prefecture_id: '29')
Gerende.create(name: '大山鏡ヶ成スキー場(鳥取)', prefecture_id: '31')
Gerende.create(name: 'だいせんホワイトリゾート(鳥取)', prefecture_id: '31')
Gerende.create(name: '大山ますみず高原スキー場　SNOW PARK', prefecture_id: '31')
Gerende.create(name: '奥大山スキー場(鳥取)', prefecture_id: '31')
Gerende.create(name: 'わかさ氷ノ山スキー場(鳥取)', prefecture_id: '31')
Gerende.create(name: '琴引フォレストパーク(島根)', prefecture_id: '32')
Gerende.create(name: 'アサヒテングストン(島根)', prefecture_id: '32')
Gerende.create(name: '三井野原スキー場(島根)', prefecture_id: '32')
Gerende.create(name: 'ひるぜんベアバレースキー場(岡山)', prefecture_id: '33')
Gerende.create(name: '津黒高原スキー場(岡山)', prefecture_id: '33')
Gerende.create(name: 'いぶきの里スキー場(岡山)', prefecture_id: '33')
Gerende.create(name: 'ひるぜんキッズスノーパーク(岡山)', prefecture_id: '33')
Gerende.create(name: '恩原高原スキー場(岡山)', prefecture_id: '33')
Gerende.create(name: '大芽スキー場(岡山)', prefecture_id: '33')
Gerende.create(name: 'スノーリゾート猫山(広島)', prefecture_id: '34')
Gerende.create(name: '恐羅漢スノーパーク(広島)', prefecture_id: '34')
Gerende.create(name: '女鹿平温泉めがひらスキー場(広島)', prefecture_id: '34')
Gerende.create(name: '芸北国際スキー場(広島)', prefecture_id: '34')
Gerende.create(name: 'やわたハイランド191リゾート(広島)', prefecture_id: '34')
Gerende.create(name: 'ひろしま県民の森スキー場(広島)', prefecture_id: '34')
Gerende.create(name: 'ユートピアサイオト(広島)', prefecture_id: '34')
Gerende.create(name: '大佐スキー場(広島)', prefecture_id: '34')
Gerende.create(name: 'もみのき森林公園スキー場(広島)', prefecture_id: '34')
Gerende.create(name: 'りんご今日話国スキー場(広島)', prefecture_id: '34')
Gerende.create(name: '道後山高原スキー場(広島)', prefecture_id: '34')
Gerende.create(name: '十種ヶ峰スキー場(山口)', prefecture_id: '35')
Gerende.create(name: '井川スキー場　腕山(徳島)', prefecture_id: '36')
Gerende.create(name: '石鎚スキー場(愛媛)', prefecture_id: '38')
Gerende.create(name: '久万スキーランド(愛媛)', prefecture_id: '38')
Gerende.create(name: 'SOL-FA オダスキーゲレンデ(愛媛)', prefecture_id: '38')
Gerende.create(name: '天狗高原スキー場(高知)', prefecture_id: '39')
Gerende.create(name: '天山スキー場(佐賀)', prefecture_id: '41')
Gerende.create(name: '九重スキー場(大分)', prefecture_id: '44')